processScheduledJobCron: 0/10 * * * * ?  # every 10 seconds

spireClientUserName: bisuat.api@test.com
spireClientPassword: sp1reUAT
spireClientUrl: https://www.spiretest.trade.gov.uk/spireuat/fox/ispire/

jwtSharedSecret: demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement

customerServiceUrl: http://customer-service.svc.dev.licensing.service.trade.gov.uk.test

maxMinutesRetryAfterFail: 1
maxCallbackFailCount: 5

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT}

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    uk.gov.bis.lite.common.spire.client: WARN

database:
  driverClass: org.postgresql.Driver
  url: ${VCAP_JDBC_URL}
  schema: permissionsvc
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1
  minSize: 1
  maxSize: 3
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: user
adminPassword: password