# processScheduledJobCron: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * ? # every 5 minutes
# processScheduledJobCron: 0/20 * * * * ?  # every 20 seconds
processScheduledJobCron: 0/10 * * * * ?  # every 10 seconds

# soapUserName: bisdev.api@test.com
# soapPassword: dev
# spireCreateOgelAppUrl: https://spiredevalpha.fivium.co.uk/spirefox4dev/fox/ispire/SPIRE_CREATE_OGEL_APP

# soapUserName: bisuat.api@test.com
# soapPassword: sp1reUAT
# spireCreateOgelAppUrl: https://www.spiretest.trade.gov.uk/spireuat/fox/ispire/SPIRE_CREATE_OGEL_APP

customerServiceUrl: http://localhost:8095
customerServiceCustomerPath: /create-customer
customerServiceSitePath: /create-site
customerServiceUserRolePath: /userRole

spireServiceUserName: bisuat.api@test.com
spireServicePassword: sp1reUAT
spireServiceUrl: https://www.spiretest.trade.gov.uk/spireuat/fox/ispire/
spireServiceActiveEndpoints: CREATE_OGEL_APP, CREATE_LITE_SAR

maxMinutesRetryAfterFail: 1

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8093
  adminConnectors:
    - type: http
      port: 8094

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: '[%d{HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] %msg %n'

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:localPermissions.db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1 # connections
  minSize: 1 # connections
  maxSize: 3 # connections
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: user
adminPassword: password