notificationRetryJobCron: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * ? # every 5 minutes

soapUserName: bisdev.api@test.com
spireOgelRegistrationsUrl: https://spiredevalpha.fivium.co.uk/spirefox4dev/fox/ispire/SPIRE_OGEL_REGISTRATIONS
soapPassword: dev

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8095

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: '[%d{HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] %msg %n'

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:localPermissions.db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1 # connections
  minSize: 1 # connections
  maxSize: 3 # connections
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: user
adminPassword: password