processScheduledJobCron: 0/10 * * * * ?  # every 10 seconds

spireClientUserName: bisuat.api@test.com
spireClientPassword: sp1reUAT
spireClientUrl: https://www.spiretest.trade.gov.uk/spireuat/fox/ispire/

customerServiceUrl: http://localhost:8095

maxMinutesRetryAfterFail: 1

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8093
  adminConnectors:
    - type: http
      port: 8094

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:localPermissions.db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1
  minSize: 1
  maxSize: 3
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: user
adminPassword: password